## Everything below is specific to the hugoBasicExample
baseURL = "https://example.com"

[params]
  description = "A Hugo port of the static html template Alpha by HTML5 UP."
  mainSections = ["post"]

## Markdown Settings
enableEmoji = true
[markup.goldmark]
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.goldmark.parser]
    attribute = true
    autoHeadingID = true
    autoHeadingIDType = "github"
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "bw"
    tabWidth = 4

## Menu Settings
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/post/"
    weight = 20
  [[menu.main]]
    identifier = "taxonomies"
    name = "Taxonomies"
    url = "#"
    weight = 30
  [[menu.main]]
    parent = "taxonomies"
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 31
  [[menu.main]]
    parent = "taxonomies"
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 31
  [[menu.main]]
    parent = "taxonomies"
    identifier = "series"
    name = "Series"
    url = "/series/"
    weight = 33

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true